kind: pipeline
name: Build

steps:
- name: build candidates spgg
  image: plugins/docker
  settings:
    username: admin
    password: Harbor12345
    repo: registry.internal.hisao.org/prod/multas-spgg-candidates
    registry: registry.internal.hisao.org
    dockerfile: Dockerfile.candidates_spgg    
    tags:
    - latest
