# Endpoints of ASP backends from where the tickets will be retrieved.
SAN_PEDRO_ASP_ENDPOINT = (
    "https://aplicativos.sanpedro.gob.mx/esanpedro/multas/estado_cuenta.asp"
)
MONTERREY_ASP_ENDPOINT = "https://asp.monterrey.gob.mx/MultasTransito/"

# Sets the amount of plates that will be considered candidates after a positive match. (Modify second value)
CANDIDATE_PLATES_AFTER_POSITIVE_MATCH = 1 + 50

# Sets the minimum time of days when a plate will be queried again, this to provide all plates an equal chance.
QUERY_COOLDOWN_DAYS = 68


cleanup_ticket_names = {
    "No paga cuota parquimetro": "MULTA DE PARQUIMETROS",
    "NO PAGAR CUOTA PARQUIMETRO": "MULTA DE PARQUIMETROS",
    "ESTACIONARSE EN LUGAR PROHIBIDO   , ART. 72 FRACC. III, IV, V, VI, VII, VIII, IX, X, XI, XII, XIII, XV, XVI, XVII, XX, X": "ESTACIONARSE EN LUGAR PROHIBIDO",
    "ESTAC EN LUGAR PROHIBIDO": "ESTACIONARSE EN LUGAR PROHIBIDO",
    "Est. En lugar Prohibido": "ESTACIONARSE EN LUGAR PROHIBIDO",
    "ESTAC. LUGAR PROHIBIDO": "ESTACIONARSE EN LUGAR PROHIBIDO",
    "ESTACIONARSE EN LUGAR PROHIBIDO   , ART. 72": "ESTACIONARSE EN LUGAR PROHIBIDO",
    "cambiar carr s/ prec": "CAMBIAR CARRIL SIN PRECAUCION",
    "REBASAR EN LUGAR PROHIBID": "REBASAR EN LUGAR PROHIBIDO",
    "SER RESPONSABLE EN HECHO DE TRÁNSITO , ART. 137": "SER RESPONSABLE EN HECHO DE TRÁNSITO",
    "circ. sin licencia o vencida": "CIRCULAR SIN LICENCIA O VENCIDA",
    "VOLTEAR A LA IZQ EN LUGAR PROH": "VOLTEAR A LA IZQUIERDA EN LUGAR PROHIBIDO",
    "TRANS.PERS.EN LUGAR PROH.": "TRANSPORTAR PERSONAS EN LUGAR PROHIBIDO",
    "SUJETAR APARATOS DE COMUNICACIÓN O APARATOS ELECTRÓNICOS , ART. 51, FRACC. II": "SUJETAR APARATOS DE COMUNICACION",
    "MANEJAR C/LIC.VENCIDA": "MANEJAR CON LICENCIA VENCIDA",
    "CIRC. ZIGZAGUEANDO": "CIRCULAR ZIGZAGUEANDO",
    "INICIAR MARCHA SIN PRECAUCIÓN , ART. 49, FRACC. XV": "INICIAR MARCHA SIN PRECAUCIÓN",
    "MANEJAR LICEN.NO ACORDE AL VEH": "MANEJAR LICENCIA NO ACORDE AL VEHICULO",
    "NO CONTAR CON CINTURON DE SEG.": "NO CONTAR CON CINTURON DE SEGURIDAD",
    "Conducir sin cinturon": "NO CONTAR CON CINTURON DE SEGURIDAD",
    "INTERVENIR EN ASUNTOS DE TRANS": "INTERVENIR EN ASUNTOS DE TRANSITO",
    "ESTACIONARSE EN LUGAR EXCLUSIVO PARA DISCAPACITADOS , ART. 72, FRACC. XVIII": "ESTACIONARSE EN LUGAR EXCLUSIVO PARA DISCAPACITADOS",
    "EXCESO DE VELOCIDAD EN ZONA ESCOLAR , ART. 52, FRACC. I": "EXCESO DE VELOCIDAD EN ZONA ESCOLAR",
    "exceso de velocidad": "EXCESO DE VELOCIDAD",
    "TRASLADO DE LESIONADO C. ROJA": "TRASLADO DE LESIONADO CRUZ ROJA",
    "EXCESO DE VELOCIDAD Z. URBANA": "EXCESO DE VELOCIDAD EN ZONA URBANA",
    "EX.VELOCIDAD ZONA URBANA": "EXCESO DE VELOCIDAD EN ZONA URBANA",
    "Exceso vel. Zona Escolar": "EXCESO DE VELOCIDAD EN ZONA ESCOLAR",
    "EXCESO DE VEL. EN Z.ESCOLAR": "EXCESO DE VELOCIDAD EN ZONA ESCOLAR",
    "EX. VELOCIDAD Z/ESCOLAR": "EXCESO DE VELOCIDAD EN ZONA ESCOLAR",
    "ABANDONAR VEHÍCULO EN VÍA PÚBLICA , ART. 105, FRACC. XVII": "ABANDONAR VEHÍCULO EN VÍA PÚBLICA",
    "REINCIDENCIA POR CONDUCIR EN EBRIEDAD INCOMPLETA , ART. 51, FRACC. I, INCISO B": "REINCIDENCIA POR CONDUCIR EN EBRIEDAD INCOMPLETA",
    "Reincid en periodo 1 anio": "REINCIDENCIA POR CONDUCIR EN EBRIEDAD COMPLETA/INCOMPLETA",
    "CONDUCIR EN ESTADO DE EBRIEDAD INCOMPLETA Y COMETER CUALQUIER OTRA INFRACCIÓN , ART. 51, FRACC. I": "CONDUCIR EN ESTADO DE EBRIEDAD INCOMPLETA Y COMETER CUALQUIER OTRA INFRACCIÓN",
    "NEGARSE A EXAMEN MÉDICO , ART. 49, FRACC. XVI": "NEGARSE A EXAMEN MÉDICO",
    "HUIR EN CASO DE HECHO DE TRÁNSITO , ART. 140, FRACC. VI": "HUIR EN CASO DE HECHO DE TRÁNSITO",
    "CONDUCIR EN ESTADO DE EBRIEDAD INCOMPLETA , ART. 51, FRACC. I": "CONDUCIR EN ESTADO DE EBRIEDAD INCOMPLETA",
    "REINCIDENCIA POR CONDUCIR EN EBRIEDAD COMPLETA , ART. 166, FRACC. I": "REINCIDENCIA POR CONDUCIR EN EBRIEDAD COMPLETA",
    "REINCIDENCIA POR CONDUCIR EN EBRIEDAD COMPLETA , ART. 51, FRACC. I, INCISO B": "REINCIDENCIA POR CONDUCIR EN EBRIEDAD COMPLETA",
    "POSEER BEBIDA ALCOHÓLICA ABIERTA , ART. 51, FRACC. XXVII": "POSEER BEBIDA ALCOHÓLICA ABIERTA",
    "CONDUCIR EN ESTADO DE EBRIEDAD COMPLETA , ART. 51, FRACC. I": "CONDUCIR EN ESTADO DE EBRIEDAD COMPLETA",
    "Manejar ebriedad completa": "CONDUCIR EN ESTADO DE EBRIEDAD COMPLETA",
    "CIRC. CON CRISTALES QUE LIMITEN VISIBILIDAD, POLARIZADOS U OPACOS , ART. 24, FRACC. VIII": "CIRCULAR CON CRISTALES QUE LIMITEN VISIBILIDAD, POLARIZADOS U OPACOS",
    "C. CON PARABRISAS SOBMRE/ASTIL": "CIRCULAR CON CRISTALES QUE LIMITEN VISIBILIDAD, POLARIZADOS U OPACOS",
    "INSULTAR, AMENAZAR O AGREDIR AL PERSONAL DE TRÁNSITO , ART. 170, FRACC. IX": "INSULTAR, AMENAZAR O AGREDIR AL PERSONAL DE TRÁNSITO",
    "VUELTA ENCARRIL PROH. Y CHOCAR": "VUELTA EN CARRIL PROHIBIDO Y CHOCAR",
    "VUELTA EN  U  L.PROH. Y CHOCAR": "VUELTA EN U EN LUGAR PROHIBIDO Y CHOCAR",
    "Dar vuelta  lugar prohi o en U": "VUELTA EN U EN LUGAR PROHIBIDO",
    "TRANSPORTAR PASAJEROS EN LUGAR PROHIBIDO , ART. 51, FRACC. IV": "TRANSPORTAR PASAJEROS EN LUGAR PROHIBIDO",
    "TRANSPORTAR PERSONAS EN LUGAR PROHIBIDO": "TRANSPORTAR PASAJEROS EN LUGAR PROHIBIDO",
    "Transp pers esp prohib": "TRANSPORTAR PASAJEROS EN LUGAR PROHIBIDO",
    "TRANS. PERSONAS LUG.PROHI": "TRANSPORTAR PASAJEROS EN LUGAR PROHIBIDO",
    "No guardar distancia": "NO GUARDAR DISTANCIA",
    "NO GUARDAR DISTANCIA , ART. 99": "NO GUARDAR DISTANCIA",
    "Interrumpir carril de  circu.": "INTERRUMPIR CARRIL DE CIRCULACIÓN",
    "Circ  hablando por telef o rad": "SUJETAR APARATOS DE COMUNICACION",
    "NO RESPETAR INDICACIONES DE POLICÍA DE TRÁNSITO , ART. 49, FRACC. I": "NO RESPETAR INDICACIONES DE POLICÍA DE TRÁNSITO",
    "No resp indic. de oficial": "NO RESPETAR INDICACIONES DE POLICÍA DE TRÁNSITO",
    "Circ. en sentido contrario.": "CIRCULAR EN SENTIDO CONTRARIO",
    "CAMBIAR DE CARRIL SIN PRECAUCIÓN  , ART. 89, FRACC. III": "CAMBIAR DE CARRIL SIN PRECAUCIÓN",
    "FALTA DE CINTURON DE SEG": "NO CONTAR CON CINTURON DE SEGURIDAD",
    "No portar tarjeta de circ.": "NO PORTAR TARJETA DE CIRCULACION",
    "NO RESPETAR SEMÁFORO , ART. 152, FRACC. III": "NO RESPETAR SEMÁFORO",
    "Poseer beb alcohol abierta": "POSEER BEBIDA ALCOHÓLICA ABIERTA",
    "NEGARSE A ENTREGAR DOCUMENTOS , ART. 49, FRACC. XIII": "NEGARSE A ENTREGAR DOCUMENTOS",
    "NO PORTAR TARJETA DE CIRC. VIGENTE , ART. 12, FRACC. III": "NO PORTAR TARJETA DE CIRCULACION",
    "CIRC. SENTIDO CONTRARIO": "CIRCULAR EN SENTIDO CONTRARIO",
    "No entreg tarj. circ. o licen": "NEGARSE A ENTREGAR DOCUMENTOS",
    "DAR VUELTA IZQ. PROHIBIDA": "DAR VUELTA IZQUIERDA PROHIBIDA"
}
