# Endpoints of ASP backends from where the tickets will be retrieved.
SAN_PEDRO_ASP_ENDPOINT = (
    "https://aplicativos.sanpedro.gob.mx/esanpedro/multas/estado_cuenta.asp"
)
MONTERREY_ASP_ENDPOINT = "https://asp.monterrey.gob.mx/MultasTransito/"

# Sets the amount of plates that will be considered candidates after a positive match. (Modify second value)
CANDIDATE_PLATES_AFTER_POSITIVE_MATCH = 1 + 20

# Sets the minimum time of days when a plate will be queried again, this to provide all plates an equal chance.
QUERY_COOLDOWN_DAYS = 68


cleanup_ticket_names = {
    "No paga cuota parquimetro": "MULTA DE PARQUIMETROS",
    "NO PAGAR CUOTA PARQUIMETRO": "MULTA DE PARQUIMETROS",
    "ESTACIONARSE EN LUGAR PROHIBIDO   , ART. 72 FRACC. III, IV, V, VI, VII, VIII, IX, X, XI, XII, XIII, XV, XVI, XVII, XX, X": "ESTACIONARSE EN LUGAR PROHIBIDO",
    "ESTAC EN LUGAR PROHIBIDO": "ESTACIONARSE EN LUGAR PROHIBIDO",
    "Est. En lugar Prohibido": "ESTACIONARSE EN LUGAR PROHIBIDO",
    "ESTAC. LUGAR PROHIBIDO": "ESTACIONARSE EN LUGAR PROHIBIDO",
    "ESTACIONARSE EN LUGAR PROHIBIDO   , ART. 72": "ESTACIONARSE EN LUGAR PROHIBIDO",
    "cambiar carr s/ prec": "CAMBIAR CARRIL SIN PRECAUCION",
    "REBASAR EN LUGAR PROHIBID": "REBASAR EN LUGAR PROHIBIDO",
    "SER RESPONSABLE EN HECHO DE TRÁNSITO , ART. 137": "SER RESPONSABLE EN HECHO DE TRÁNSITO",
    "circ. sin licencia o vencida": "CIRCULAR SIN LICENCIA O VENCIDA",
    "VOLTEAR A LA IZQ EN LUGAR PROH": "VOLTEAR A LA IZQUIERDA EN LUGAR PROHIBIDO",
    "TRANS.PERS.EN LUGAR PROH.": "TRANSPORTAR PERSONAS EN LUGAR PROHIBIDO",
    "SUJETAR APARATOS DE COMUNICACIÓN O APARATOS ELECTRÓNICOS , ART. 51, FRACC. II": "SUJETAR APARATOS DE COMUNICACION",
    "MANEJAR C/LIC.VENCIDA": "MANEJAR CON LICENCIA VENCIDA",
    "CIRC. ZIGZAGUEANDO": "CIRCULAR ZIGZAGUEANDO",
    "INICIAR MARCHA SIN PRECAUCIÓN , ART. 49, FRACC. XV": "INICIAR MARCHA SIN PRECAUCIÓN",
    "MANEJAR LICEN.NO ACORDE AL VEH": "MANEJAR LICENCIA NO ACORDE AL VEHICULO",
    "NO CONTAR CON CINTURON DE SEG.": "NO CONTAR CON CINTURON DE SEGURIDAD",
    "INTERVENIR EN ASUNTOS DE TRANS": "INTERVENIR EN ASUNTOS DE TRANSITO",
    "ESTACIONARSE EN LUGAR EXCLUSIVO PARA DISCAPACITADOS , ART. 72, FRACC. XVIII": "ESTACIONARSE EN LUGAR EXCLUSIVO PARA DISCAPACITADOS",
    "EXCESO DE VELOCIDAD EN ZONA ESCOLAR , ART. 52, FRACC. I": "EXCESO DE VELOCIDAD EN ZONA ESCOLAR",
    "exceso de velocidad": "EXCESO DE VELOCIDAD",
    "TRASLADO DE LESIONADO C. ROJA": "TRASLADO DE LESIONADO CRUZ ROJA",
    "EXCESO DE VELOCIDAD Z. URBANA": "EXCESO DE VELOCIDAD EN ZONA URBANA",
    "Exceso vel. Zona Escolar": "EXCESO DE VELOCIDAD EN ZONA ESCOLAR",
    "EXCESO DE VEL. EN Z.ESCOLAR": "EXCESO DE VELOCIDAD EN ZONA ESCOLAR",
}
